### ISSUE TITLE
批量更新，未进行字段更新报错

### ISSUE THREAD

**Issue by nihf** [GeeQuery/ef-orm#87]
session的batchUpdate0的
for (int i = 0; i < 3 ; i++) {
	template = entities.get(i);
	if (!dyna || template.needUpdate()) {
		break;
	}
}
如果entities<3 则报错

**Comment by xuse** [comment]
这个问题上次我们也发现了，已修改。多谢 来自360手机 在2017年06月28日 20:38 ，nihaifeng写道： session的batchUpdate0的 for (int i = 0; i < 3 ; i++) { template = entities.get(i); if (!dyna || template.needUpdate()) { break; } } 如果entities<3 则报错 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
